packages:
  - 'packages/*'
  - 'examples/*'
  - 'speajus.github.io'
# Define a catalog of version ranges.
catalog:
  "@types/node": ^22.9.0
  "@vitest/coverage-v8": ^2.1.5
  prettier: ^3.3.3
  typescript: ^5.7.2
  vite-tsconfig-paths: ^5.1.2
  vitest: ^2.1.5
  tsx: "^4.19.2"
  