name: Prettier Formatting

on:
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/pea
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Check Prettier
        run: npm run prettier:check
      - name: Build
        run: npm build
      - name: Test
        run: npm test
