name: Prettier Formatting

on:
  pull_request:
    branches:
      - "**"
jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/pea
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: '--write **/*.{js,ts,tsx,json,md,css}'
          github_token: ${{ secrets.GITHUB_TOKEN }}