name: Prettier Formatting

on:
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/pea
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile   
      - run: yarn run prettier:check
      - run: yarn build
      - run: yarn test
